Repository BinaryStudioAcademy/bsa-2022-streamlet, pull requests merged in 2022-08, with the labels that each got.

#8 Task/backend4-add-api-docs
  backend/package.json
  backend/src/app.ts
  backend/src/configuration/swagger.ts
  backend/src/primary-adapters/rest/auth/auth-controller.ts
  backend/src/primary-adapters/rest/rest-container-module.ts
  backend/src/primary-adapters/rest/user/user-controller.ts
  package-lock.json
Labels: documentation

#54 Fix/frontend52 add close icon
  frontend/src/assets/img/close.svg
  frontend/src/common/enums/components/icon-name.enum.ts
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/common/modal/modal.tsx
  frontend/src/components/common/modal/styles.module.scss
Labels: fix

#53 Fix/backend20: * fixed type definitions for test route
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
Labels: fix

#34 Task/frontend43 add search page
  frontend/src/assets/css/breakpoint.scss
  frontend/src/assets/img/arrow-down.svg
  frontend/src/assets/img/arrow-up.svg
  frontend/src/assets/img/filter.svg
  frontend/src/assets/img/play.svg
  frontend/src/assets/img/xmark.svg
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/enums/components/icon-name.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/search/search.ts
  frontend/src/common/types/components/components.ts
  frontend/src/common/types/types.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.tsx
  frontend/src/components/common/header/header-container.tsx
  frontend/src/components/common/header/header.module.scss
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/search/components/common/common.tsx
  frontend/src/components/search/components/common/filter-bar-select/filter-bar-select.tsx
  frontend/src/components/search/components/common/filter-bar-select/styles.module.scss
  frontend/src/components/search/components/common/filter-dropdown/filter-dropdown.tsx
  frontend/src/components/search/components/common/filter-dropdown/styles.module.scss
  frontend/src/components/search/components/common/filter-select/filter-select.tsx
  frontend/src/components/search/components/common/filter-select/styles.module.scss
  frontend/src/components/search/components/common/video-tag/styles.module.scss
  frontend/src/components/search/components/common/video-tag/video-tag.tsx
  frontend/src/components/search/components/components.tsx
  frontend/src/components/search/components/filter-bar/filter-bar.tsx
  frontend/src/components/search/components/filter-bar/styles.module.scss
  frontend/src/components/search/components/filter-sidebar/filter-sidebar.tsx
  frontend/src/components/search/components/filter-sidebar/styles.module.scss
  frontend/src/components/search/components/result-not-found/result-not-found.tsx
  frontend/src/components/search/components/result-not-found/styles.module.scss
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/components/search/components/video-card/video-card.tsx
  frontend/src/components/search/config/config.ts
  frontend/src/components/search/config/date-filter.config.ts
  frontend/src/components/search/config/duration-filter.config.ts
  frontend/src/components/search/config/sort-by-filter.config.ts
  frontend/src/components/search/config/type-filter.config.ts
  frontend/src/components/search/helpers.ts
  frontend/src/components/search/search.tsx
  frontend/src/components/search/styles.module.scss
  frontend/src/hooks/hooks.ts
  frontend/src/pages/main-page/index.tsx
  frontend/src/services/http/interceptors/refresh-token-interceptor.ts
  frontend/src/store/actions.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/search/actions.ts
  frontend/src/store/search/common.ts
  frontend/src/store/search/models.ts
  frontend/src/store/search/reducer.ts
  frontend/src/store/store.ts
  shared/src/common/types/components/components.ts
  shared/src/common/types/components/video-card/video-card.ts
  shared/src/common/types/components/video-card/video-card.type.ts
  shared/src/common/types/types.ts
Labels: enhancement

#60 Fix/backend65 swagger documentation
  backend/core/src/configuration/swagger.ts
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
  backend/core/src/primary-adapters/rest/user/user-controller.ts
Labels: fix

#78 Fix/frontend86 linking pages
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
  backend/core/src/primary-adapters/rest/user/user-controller.ts
  frontend/src/assets/css/scaffolding.scss
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/http/http.ts
  frontend/src/common/types/toast-notification/toast-notification-params.type.ts
  frontend/src/common/types/toast-notification/toast-notifications.ts
  frontend/src/common/types/types.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/auth/components/restore-password-form/restore-password-form.tsx
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-up-form/common.ts
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/components/auth/config/auth-notification/auth-notification-icon-name.config.ts
  frontend/src/components/auth/config/auth-notification/auth-notification-message.config.ts
  frontend/src/components/auth/config/auth-notification/auth-notification-title.config.ts
  frontend/src/components/auth/config/auth-notification/auth-notification-type.config.ts
  frontend/src/components/auth/config/auth-notification/auth-notification.config.ts.ts
  frontend/src/components/auth/config/auth-notification/auth-notification.ts
  frontend/src/components/auth/config/config.ts
  frontend/src/components/auth/sign-in-page.tsx
  frontend/src/components/auth/sign-up-page.tsx
  frontend/src/components/common/common.tsx
  frontend/src/components/common/errors/error-box/error-box.module.scss
  frontend/src/components/common/header/config.ts
  frontend/src/components/common/header/header-container.tsx
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/header/helpers.ts
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/common/input/input-component.tsx
  frontend/src/components/common/input/password-input/password-input.tsx
  frontend/src/components/common/toast-notification/toast-notification.tsx
  frontend/src/components/common/toast-notification/toast-notifications.tsx
  frontend/src/hooks/hooks.ts
  frontend/src/hooks/use-app-form/use-app-form.hook.ts
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/http.service.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/reducer.ts
  shared/src/common/enums/api/auth-api-path.enum.ts
  shared/src/common/enums/http/http-code.enum.ts
  shared/src/common/enums/user/user-validation-message.enum.ts
  shared/src/common/types/user/user-sign-up-request-dto.type.ts
  shared/src/validation-schemas/user/refresh-password-validation-schema.ts
  shared/src/validation-schemas/user/user-sign-up.validation-schema.ts
Labels: fix

#80 fix/frontend76-sign-btn-loader
  frontend/src/common/enums/component/component.ts
  frontend/src/common/enums/component/loader-size.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/components/auth/components/common/auth-submit-btn/auth-submit-btn.tsx
  frontend/src/components/common/loader/loader.tsx
  frontend/src/index.tsx
Labels: fix

#94 Fix/frontend-143: - commented redux actions calls to remove console 404 errors
  frontend/src/components/notification-dropdown/notification-dropdown-container.tsx
Labels: fix

#93 Fix/frontend96 search components
  frontend/src/assets/css/scaffolding.scss
  frontend/src/assets/img/circle.svg
  frontend/src/assets/img/default-video-poster.jpg
  frontend/src/common/enums/component/icon-name.enum.ts
  frontend/src/common/types/types.ts
  frontend/src/common/types/video/video.ts
  frontend/src/components/common/header/header-container.tsx
  frontend/src/components/common/header/header.module.scss
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/common/toggle-switch/styles.module.scss
  frontend/src/components/common/video-card-main/components/components.ts
  frontend/src/components/common/video-card-main/components/scheduled-video-badge/scheduled-video-badge.tsx
  frontend/src/components/common/video-card-main/config.ts
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/common/video-card-main/video-card-main.tsx
  frontend/src/components/search/components/common/filter-dropdown/filter-dropdown.tsx
  frontend/src/components/search/components/common/filter-dropdown/styles.module.scss
  frontend/src/components/search/components/common/filter-select/filter-select.tsx
  frontend/src/components/search/components/common/filter-select/styles.module.scss
  frontend/src/components/search/components/common/video-tag/styles.module.scss
  frontend/src/components/search/components/filter-bar/styles.module.scss
  frontend/src/components/search/components/filter-sidebar/filter-sidebar.tsx
  frontend/src/components/search/components/filter-sidebar/styles.module.scss
  frontend/src/components/search/components/video-card/components/components.tsx
  frontend/src/components/search/components/video-card/components/meta-data-video/meta-data-video.tsx
  frontend/src/components/search/components/video-card/components/meta-data-wait/meta-data-wait.tsx
  frontend/src/components/search/components/video-card/components/scheduled-video-badge/scheduled-video-badge.tsx
  frontend/src/components/search/components/video-card/config.ts
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/components/search/components/video-card/video-card.tsx
  frontend/src/components/search/helpers.ts
  frontend/src/components/search/search.tsx
  frontend/src/components/search/styles.module.scss
  frontend/src/helpers/helpers.ts
  frontend/src/helpers/video/get-format-duration-string.helper.ts
  frontend/src/helpers/video/get-format-scheduled-date-string.helper.ts
  frontend/src/helpers/video/video.ts
  frontend/src/services/video-api/video-api.service.ts
Labels: fix

#95 Task/frontend123 base styles fix font connect
  frontend/src/assets/css/scaffolding.scss
  frontend/src/assets/font/Gilroy-Medium.woff
  frontend/src/assets/font/Gilroy-Regular.woff
  frontend/src/assets/font/Gilroy-SemiBold.woff
  frontend/src/assets/fonts/Gilroy-Black.woff2
  frontend/src/assets/fonts/Gilroy-BlackItalic.woff2
  frontend/src/assets/fonts/Gilroy-Bold.woff2
  frontend/src/assets/fonts/Gilroy-BoldItalic.woff2
  frontend/src/assets/fonts/Gilroy-Extrabold.woff2
  frontend/src/assets/fonts/Gilroy-ExtraboldItalic.woff2
  frontend/src/assets/fonts/Gilroy-Heavy.woff2
  frontend/src/assets/fonts/Gilroy-HeavyItalic.woff2
  frontend/src/assets/fonts/Gilroy-Light.woff2
  frontend/src/assets/fonts/Gilroy-LightItalic.woff2
  frontend/src/assets/fonts/Gilroy-Medium.woff2
  frontend/src/assets/fonts/Gilroy-MediumItalic.woff2
  frontend/src/assets/fonts/Gilroy-Regular.woff2
  frontend/src/assets/fonts/Gilroy-RegularItalic.woff2
  frontend/src/assets/fonts/Gilroy-Semibold.woff2
  frontend/src/assets/fonts/Gilroy-SemiboldItalic.woff2
  frontend/src/assets/fonts/Gilroy-Thin.woff2
  frontend/src/assets/fonts/Gilroy-ThinItalic.woff2
  frontend/src/assets/fonts/Gilroy-UltraLight.woff2
  frontend/src/assets/fonts/Gilroy-UltraLightItalic.woff2
  frontend/src/components/auth/components/common/continue-with-paragraph/styles.module.scss
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/search/components/common/filter-dropdown/styles.module.scss
  frontend/src/components/search/components/common/filter-select/styles.module.scss
  frontend/src/components/search/components/video-card/styles.module.scss
Labels: fix

#96 frontend-125: - eslint error
  frontend/src/components/common/sidebar/sidebar-container.tsx
Labels: fix

#97 Fix/common127 fix refresh flow
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
  frontend/src/common/types/user/user.ts
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/interceptors/attach-auth-token-interceptor.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/common.ts
Labels: fix

#100 frontend-137: * fix 'jumping' sidebar links
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.module.scss
  frontend/src/components/common/sidebar/sidebar.module.scss
Labels: fix

#102 Fix successful registration message
  backend/core/src/shared/enums/messages/success-messages.ts
Labels: fix

#105 Fix/frontend139 fix light theme
  frontend/src/components/common/video-skeleton/video-skeleton.config.ts
  frontend/src/components/common/videos-block/videos-block.tsx
Labels: fix

#111 Fix/frontend146 video card
  frontend/src/assets/img/default-video-poster-dark.jpg
  frontend/src/assets/img/default-video-poster-light.jpg
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/common/video-card-main/video-card-main.tsx
  frontend/src/components/common/videos-block/videos-block.tsx
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/components/search/components/video-card/video-card.tsx
  frontend/src/components/search/search.tsx
  frontend/src/components/search/styles.module.scss
Labels: fix

#115 frontend-140: * fix upload user avatar
  frontend/src/components/common/image-editor/image-editor.tsx
  frontend/src/pages/profile-preferences-page/profile-preferences-page.tsx
Labels: fix

#116 Fix/frontend streamline auth layout
  frontend/src/assets/css/scaffolding.scss
  frontend/src/assets/img/password-eye.svg
  frontend/src/components/auth/components/auth-container/auth-container.tsx
  frontend/src/components/auth/components/auth-container/styles.module.scss
  frontend/src/components/auth/components/common/auth-submit-btn/auth-submit-btn.tsx
  frontend/src/components/auth/components/common/auth-submit-btn/styles.module.scss
  frontend/src/components/auth/components/common/continue-with-paragraph/continue-with-paragraph.tsx
  frontend/src/components/auth/components/common/continue-with-paragraph/styles.module.scss
  frontend/src/components/auth/components/common/social-buttons/google-button/styles.module.scss
  frontend/src/components/auth/components/error-display-with-code/error-display-with-code.tsx
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/auth/components/restore-password-form/restore-password-form.tsx
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-in-form/styles.module.scss
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/components/common/input/password-input/password-input.module.scss
  frontend/src/components/common/input/password-input/password-input.tsx
  frontend/src/components/common/input/styles.module.scss
  frontend/src/pages/account-verification-page/account-verification-confirm-page.tsx
  frontend/src/pages/account-verification-page/account-verification-init-page.tsx
  frontend/src/pages/account-verification-page/send-verification-link-form/send-verification-link-form.tsx
Labels: fix

#117 Fix/backend103 sign up dublicate users
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
  backend/core/src/shared/helpers/compare-strings-insensitive.ts
  backend/core/src/shared/helpers/index.ts
Labels: fix

#118 frontend: * add max-width
  frontend/src/components/auth/components/auth-container/styles.module.scss
Labels: fix

#107 frontend-136: * fix validation hints logic
  frontend/src/components/auth/components/restore-password-form/restore-password-form.tsx
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
Labels: fix

#119 Fix/frontend135 auth styles and website color scheme
  frontend/src/assets/css/scaffolding.scss
  frontend/src/assets/img/auth/auth-curve1.svg
  frontend/src/assets/img/auth/auth-curve2.svg
  frontend/src/assets/img/auth/auth-zigzag.svg
  frontend/src/components/auth/components/auth-container/auth-container.tsx
  frontend/src/components/auth/components/auth-container/styles.module.scss
  frontend/src/components/auth/components/common/auth-submit-btn/styles.module.scss
  frontend/src/components/auth/components/common/continue-with-paragraph/styles.module.scss
  frontend/src/components/auth/components/common/social-buttons/google-button/styles.module.scss
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-in-form/styles.module.scss
  frontend/src/components/common/filters-block/filters-block.module.scss
  frontend/src/components/common/header/header.module.scss
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/image-editor/styles.module.scss
  frontend/src/components/common/input/input-component.tsx
  frontend/src/components/common/input/password-input/password-input.module.scss
  frontend/src/components/common/input/password-input/password-input.tsx
  frontend/src/components/common/input/styles.module.scss
  frontend/src/components/common/logo/logo.module.scss
  frontend/src/components/common/logo/logo.tsx
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.module.scss
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.tsx
  frontend/src/components/common/sidebar/sidebar.module.scss
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/not-found-page/styles.module.scss
  frontend/src/components/notification-dropdown/styles.module.scss
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/pages/account-verification-page/send-verification-link-form/send-verification-link-form.tsx
  frontend/src/pages/profile-preferences-page/styles.module.scss
  frontend/src/pages/restore-password-confirm-page/select-new-password-form/select-new-password-form.tsx
Labels: fix

#120 Fix/frontend-147: * bad text display fixed
  frontend/src/components/auth/components/auth-container/styles.module.scss
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-in-form/styles.module.scss
Labels: fix

#121 Fix/frontend150 video card title hover
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/common/video-card-main/video-card-main.tsx
  frontend/src/components/search/components/common/filter-dropdown/filter-dropdown.tsx
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/components/search/components/video-card/video-card.tsx
Labels: fix

#122 Fix profile page styles
  frontend/src/pages/profile-preferences-page/common/profile-preferences-page-form.tsx
  frontend/src/pages/profile-preferences-page/profile-preferences-page.tsx
  frontend/src/pages/profile-preferences-page/styles.module.scss
Labels: fix

#123 Fix/frontend-133: * fixed validation schema errors display
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/common/input/input-component.tsx
  frontend/src/components/common/input/password-input/password-input.tsx
  frontend/src/components/common/input/styles.module.scss
  shared/src/common/enums/user/user-validation-message.enum.ts
Labels: fix

#124 Fix/frontend-133: * Fixed bug with long line display
  frontend/src/components/auth/components/form-controls.module.scss
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/components/common/input/password-input/password-input.tsx
Labels: fix

#129 Task/frotnend153 fix profile page style
  frontend/src/components/common/image-editor/image-editor.tsx
  frontend/src/hooks/hooks.ts
  frontend/src/hooks/use-window-dimension/use-window-dimension.ts
  frontend/src/pages/profile-preferences-page/styles.module.scss
Labels: fix

#130 Task/frontend85 header sidebar changes
  frontend/src/assets/css/config.scss
  frontend/src/assets/css/scaffolding.scss
  frontend/src/assets/img/chevron-down.svg
  frontend/src/assets/img/chevron-up.svg
  frontend/src/assets/img/default-channel-avatar.jpg
  frontend/src/assets/img/time-ago.svg
  frontend/src/common/enums/component/icon-name.enum.ts
  frontend/src/common/types/subscription/subscription.ts
  frontend/src/common/types/types.ts
  frontend/src/components/app/app.module.scss
  frontend/src/components/auth/components/common/auth-submit-btn/styles.module.scss
  frontend/src/components/common/header/header-container.tsx
  frontend/src/components/common/header/header.module.scss
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/common/loader/styles.module.scss
  frontend/src/components/common/logo/logo.module.scss
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.module.scss
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.tsx
  frontend/src/components/common/sidebar/config.ts
  frontend/src/components/common/sidebar/sidebar-container.tsx
  frontend/src/components/common/sidebar/sidebar.module.scss
  frontend/src/components/common/sidebar/sidebar.tsx
  frontend/src/components/common/sidebar/subscription-list.mock.ts
  frontend/src/components/common/toggle-switch/styles.module.scss
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/common/video-card-main/video-card-main.tsx
  frontend/src/components/notification-dropdown/styles.module.scss
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/components/search/components/video-card/video-card.tsx
  frontend/src/components/sidebar/channel/channel.module.scss
  frontend/src/components/sidebar/channel/index.tsx
  frontend/src/components/sidebar/promo/index.tsx
  frontend/src/helpers/helpers.ts
  frontend/src/helpers/video/get-text-formated-views-string.helper.ts
  frontend/src/helpers/video/video.ts
  frontend/src/pages/video/video-page.module.scss
  shared/src/common/types/subscription/base-subscription-response-dto.type.ts
  shared/src/common/types/subscription/subscription.ts
  shared/src/common/types/types.ts
Labels: enhancement

#136 frontend-148: * fix loader
  frontend/src/pages/profile-preferences-page/common/profile-preferences-page-form.tsx
  frontend/src/pages/profile-preferences-page/styles.module.scss
Labels: fix

#137 frontend-132: * studio sidebar styles
  frontend/src/assets/css/scaffolding.scss
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.module.scss
  frontend/src/pages/studio/common/sidebar/styles.module.scss
Labels: fix

#141 Fix/profile page
  backend/core/src/secondary-adapters/postgres/profile/profile-repositoty-adapter.ts
  frontend/src/assets/img/profile.svg
  frontend/src/assets/img/zoom-in.svg
  frontend/src/common/enums/component/icon-name.enum.ts
  frontend/src/components/common/icon/icon.tsx
  frontend/src/components/common/image-editor/image-editor.tsx
  frontend/src/components/common/image-editor/styles.module.scss
  frontend/src/pages/profile-preferences-page/profile-preferences-page.tsx
  frontend/src/pages/profile-preferences-page/styles.module.scss
Labels: fix

#144 frontend-152: * fix validation mode
  frontend/src/components/auth/components/restore-password-form/restore-password-form.tsx
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/components/common/input/input-component.tsx
  frontend/src/components/common/input/password-input/password-input.tsx
  frontend/src/pages/account-verification-page/send-verification-link-form/send-verification-link-form.tsx
  frontend/src/pages/profile-preferences-page/common/profile-preferences-page-form.tsx
  frontend/src/pages/restore-password-confirm-page/select-new-password-form/select-new-password-form.tsx
Labels: fix

#142 frontend-155: * replace jpeg label by jpg
  frontend/src/pages/profile-preferences-page/profile-preferences-page.tsx
Labels: fix

#145 frontend-152: * rename labels
  frontend/src/components/auth/components/restore-password-form/restore-password-form.tsx
  frontend/src/components/auth/config/auth-notification/auth-notification-message.config.ts
Labels: fix

#131 Fix/frontend165 loading animation
  dist/styles/styles.module.css
  dist/styles/styles.module.css.map
  frontend/src/components/auth/components/common/auth-submit-btn/auth-submit-btn.tsx
  frontend/src/components/common/loader/loader.tsx
  frontend/src/components/common/loader/styles.module.scss
  frontend/src/pages/account-verification-page/account-verification-confirm-page.tsx
  frontend/src/pages/profile-preferences-page/common/profile-preferences-page-form.tsx
Labels: fix

#149 Healthcheck and labeller
  .docker/backend.Dockerfile
  .docker/docker-compose.dev.yml
  .docker/docker-compose.yml
  .docker/healthcheck.sh
  .github/labeler-config.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/labeller.yml
  backend/push/src/app.ts
  backend/push/src/server.ts
  backend/push/src/services/amqp/amqp-service.ts
Labels: ci/cd, docker, push-server

#152 Add the way to rollback the Prisma migrations in staging instance
  .docker/healthcheck.sh
  .github/workflows/deploy-dev.yml
Labels: ci/cd, docker

#153 frontend-184: * video card styles
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/search/components/video-card/styles.module.scss
  frontend/src/helpers/date/get-how-long-ago-string/get-how-long-ago-string.helper.ts
Labels: fix, frontend

#154 Fix/frontend180 fix colors for duration badge
  frontend/src/assets/css/scaffolding.scss
  frontend/src/components/common/video-card-main/styles.module.scss
  frontend/src/components/common/videos-block/videos-block.tsx
Labels: fix, frontend

#155 frontend-42: * fix layout a bit
  frontend/src/assets/img/thumb-down.svg
  frontend/src/assets/img/thumb-up.svg
  frontend/src/components/common/text-area/styles.module.scss
  frontend/src/components/common/video-player/video-player.tsx
  frontend/src/components/video-chat/video-chat.module.scss
  frontend/src/components/video-chat/video-comment/video-comment.module.scss
  frontend/src/components/video-chat/video-comment/video-comment.tsx
  frontend/src/pages/video/common/add-comment-form/add-comment-form.tsx
  frontend/src/pages/video/common/add-comment-form/styles.module.scss
  frontend/src/pages/video/common/comment-block/comment-block.tsx
  frontend/src/pages/video/common/comment-block/styles.module.scss
  frontend/src/pages/video/video-page-container.tsx
  frontend/src/pages/video/video-page.module.scss
Labels: frontend

#156 Fix/frontend186 fix resize video cards
  frontend/src/components/common/videos-block/videos-block.module.scss
Labels: fix, frontend

#157 Task/frontend 174 videos by category blocks
  backend/core/prisma/seed.ts
  frontend/src/components/common/filters-block/filter-list.mock.ts
  frontend/src/components/common/filters-block/filters-block.module.scss
  frontend/src/components/common/filters-block/index.tsx
  frontend/src/pages/main-page/main-page-container.tsx
  frontend/src/services/category-api/category-api.service.ts
  frontend/src/services/services.ts
  frontend/src/store/actions.ts
  frontend/src/store/categories/actions.ts
  frontend/src/store/categories/common.ts
  frontend/src/store/categories/reducer.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/store.ts
  frontend/src/store/videos/actions.ts
  frontend/src/store/videos/common.ts
  frontend/src/store/videos/reducer.ts
Labels: core-server, frontend

#159 frontend-174: + clear filters button for categories on the main page
  frontend/src/components/common/filters-block/index.tsx
  frontend/src/components/common/video-skeleton/video-skeleton.config.ts
  frontend/src/pages/main-page/main-page-container.tsx
  frontend/src/store/categories/actions.ts
  frontend/src/store/categories/common.ts
  frontend/src/store/categories/reducer.ts
Labels: frontend

#160 Fix/frontend42 fix video page style part 2
  backend/core/src/core/video/application/video-service.ts
  backend/core/src/primary-adapters/rest/video/video-controller.ts
  backend/core/src/secondary-adapters/postgres/video/video-repository-adapter.ts
  frontend/src/pages/video/common/add-comment-form/add-comment-form.tsx
  frontend/src/pages/video/common/add-comment-form/styles.module.scss
  frontend/src/pages/video/common/sign-in-modal/sign-in-modal.tsx
  frontend/src/pages/video/common/sign-in-modal/styles.module.scss
  frontend/src/pages/video/video-page-container.tsx
  frontend/src/pages/video/video-page.module.scss
Labels: fix, core-server, frontend

#161 common-109: + add subscription on channel page
  backend/core/src/primary-adapters/rest/channel-crud/channel-crud-controller.ts
  backend/core/src/primary-adapters/rest/middleware/base-authentication-middleware.ts
  backend/core/src/shared/helpers/trim-channel-info.ts
  frontend/src/assets/css/scaffolding.scss
  frontend/src/components/common/sign-in-modal/sign-in-modal.tsx
  frontend/src/components/common/sign-in-modal/styles.module.scss
  frontend/src/components/common/subscribe-button/styles.module.scss
  frontend/src/components/common/subscribe-button/subscribe-button.tsx
  frontend/src/pages/channel-page/components/channel-header/channel-header.tsx
  frontend/src/pages/channel-page/components/channel-header/styles.module.scss
  frontend/src/pages/channel-page/components/channel-header/subscribe/subscribe.tsx
  frontend/src/pages/video/video-page-container.tsx
  frontend/src/pages/video/video-page.module.scss
  frontend/src/store/channel/actions.ts
  frontend/src/store/channel/common.ts
  frontend/src/store/channel/reducer.ts
  shared/src/common/types/channel/channel-details/channel-info-response-dto.ts
Labels: core-server, frontend, shared

#150 frontend-181: * change white color to always white color
  frontend/src/components/common/toast-notification/styles.module.scss
Labels: frontend

#163 frontend38: * fix controls' colors in light theme
  frontend/src/assets/css/scaffolding.scss
  frontend/src/components/common/video-player/play-pause-center-effect/styles.module.scss
  frontend/src/components/common/video-player/video-player-controls/live-indicator/styles.module.scss
  frontend/src/components/common/video-player/video-player-controls/progress-bar/styles.module.scss
  frontend/src/components/common/video-player/video-player-controls/settings-control/modal-item/styles.module.scss
  frontend/src/components/common/video-player/video-player-controls/styles.module.scss
  frontend/src/components/common/video-player/video-player-controls/volume-wrapper/volume-input/styles.module.scss
Labels: frontend

#164 backend-189: + channel avatars to seed data
  backend/core/prisma/seed-data/channels.ts
Labels: core-server

#162 frontend-42: * fix modal and comment add form
  frontend/src/pages/video/common/add-comment-form/add-comment-form.tsx
  frontend/src/pages/video/common/add-comment-form/styles.module.scss
  frontend/src/pages/video/video-page.module.scss
Labels: fix, frontend

#167 Task/backend182 add first part of video data
  backend/core/prisma/seed-data/videos.ts
Labels: core-server

#169 Fix/backend 115 categories tags managment
  backend/core/src/primary-adapters/rest/category/category-controller.ts
  backend/core/src/primary-adapters/rest/tag/tag-controller.ts
  frontend/src/components/common/filters-block/filters-block.module.scss
  frontend/src/components/common/filters-block/index.tsx
Labels: core-server, frontend

#170 frontend-191: + temporary mock for real channels in sidebar
  frontend/src/components/common/sidebar/sidebar.tsx
  frontend/src/components/common/sidebar/subscription-list.mock.ts
Labels: frontend

#171 Task/backend192 implement sorting video
  backend/core/src/secondary-adapters/postgres/video/video-repository-adapter.ts
Labels: core-server

#172 backend-197: - bannerImage placeholder from one of channel seeds
  backend/core/prisma/seed-data/channels.ts
Labels: core-server

#173 frontend: - remove unneccessary onBlur and onFocus in Input
  frontend/src/components/common/input/input-component.tsx
Labels: frontend

#174 Fix/frontend199 fix disappearing video
  frontend/src/components/common/videos-block/videos-block.tsx
  frontend/src/pages/channel-page/components/video-section/video-section.tsx
  frontend/src/pages/main-page/main-page.tsx
  frontend/src/store/channel/reducer.ts
Labels: frontend

#175 frontend-42: * fix video page styles
  frontend/src/common/enums/component/icon-color.enum.ts
  frontend/src/helpers/video/get-react-button-color.helper.ts
  frontend/src/pages/video/video-page.module.scss
Labels: fix, frontend

#179 deployment: * fix backend healthcheck
  .docker/docker-compose.dev.yml
  .docker/docker-compose.yml
  backend/core/src/primary-adapters/rest/healthcheck/healthcheck-controller.ts
  backend/core/src/primary-adapters/rest/rest-container-module.ts
  backend/core/src/shared/types/container-type-keys.ts
Labels: docker, core-server

#177 Task/frontend99 add google authorization
  backend/core/.env.example
  backend/core/package.json
  backend/core/src/configuration/config.ts
  backend/core/src/configuration/google-oauth.ts
  backend/core/src/core/profile/port/profile-repository.ts
  backend/core/src/core/user/application/user-service.ts
  backend/core/src/primary-adapters/rest/auth/auth-controller.ts
  backend/core/src/primary-adapters/rest/middleware/google-middleware.ts
  backend/core/src/primary-adapters/rest/middleware/index.ts
  backend/core/src/secondary-adapters/postgres/profile/profile-repositoty-adapter.ts
  backend/core/src/shared/types/express/extended-request.ts
  backend/core/src/shared/types/user/user.ts
  backend/push/package.json
  backend/video-transcoding-server/package.json
  frontend/.env.example
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/types/user/user.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/auth/components/common/social-buttons/google-button/google-authorization.tsx
  frontend/src/components/auth/components/common/social-buttons/google-button/google-button.tsx
  frontend/src/components/auth/components/common/social-buttons/google-button/styles.module.scss
  frontend/src/helpers/user/get-google-url.ts
  frontend/src/helpers/user/index.ts
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/common.ts
  package-lock.json
  shared/src/common/enums/api/auth-api-path.enum.ts
  shared/src/common/types/user/google-request-dto.type.ts
  shared/src/common/types/user/google-response-dto.type.ts
  shared/src/common/types/user/google-user-result-dto.type.ts
  shared/src/common/types/user/user.ts
Labels: push-server, core-server, frontend, root, transcoding-server, shared

#178 Task/backend 188 channel settings api
  backend/core/src/core/channel-crud/application/channel-crud-service.ts
  backend/core/src/core/channel-crud/application/dtos/cast-to-channel-update-response-dtp.ts
  backend/core/src/core/channel-crud/port/channel-crud-repository.ts
  backend/core/src/primary-adapters/rest/channel-crud/channel-crud-controller.ts
  backend/core/src/primary-adapters/rest/middleware/channel-owner-middleware.ts
  backend/core/src/primary-adapters/rest/middleware/index.ts
  backend/core/src/primary-adapters/rest/rest-container-module.ts
  backend/core/src/secondary-adapters/cloudinary/cloudinary-container-module.ts
  backend/core/src/secondary-adapters/cloudinary/config/config.ts
  backend/core/src/secondary-adapters/cloudinary/config/presets.ts
  backend/core/src/secondary-adapters/postgres/channel-crud/channel-crud-repository-adapter.ts
  backend/core/src/shared/types/container-type-keys.ts
  shared/src/common/enums/api/channel-crud-api-path.enum.ts
  shared/src/common/enums/cloudinary/image-store-preset.enum.ts
  shared/src/common/types/channel/channel-details/channel-details.ts
  shared/src/common/types/channel/channel-details/channel-profile-update-dto.ts
  shared/src/common/types/channel/channel-details/channel-profile-update-media-request.ts
  shared/src/common/types/channel/channel-details/channel-profile-update-media.ts
  shared/src/common/types/channel/channel-details/channel-profile-update-request-dto.ts
  shared/src/common/types/channel/channel-details/channel-profile-update-response-dto.ts
Labels: core-server, shared

#180 Task/backend208 disable chat
  .docker/frontend.Dockerfile
  backend/core/prisma/migrations/20220830114036_add_live_chat_toggle/migration.sql
  backend/core/prisma/schema.prisma
  backend/core/prisma/seed-data/videos.ts
  backend/core/src/core/channel-streaming/application/channel-streaming-service.ts
  backend/core/src/core/channel-streaming/port/channel-streaming-repository.ts
  backend/core/src/core/chat/application/chat-service.ts
  backend/core/src/core/chat/port/chat-repository.ts
  backend/core/src/primary-adapters/rest/channel-streaming/channel-streaming-controller.ts
  backend/core/src/primary-adapters/rest/chat/chat-controller.ts
  backend/core/src/primary-adapters/rest/profile/profile-controller.ts
  backend/core/src/primary-adapters/rest/user/user-controller.ts
  backend/core/src/primary-adapters/rest/video/video-controller.ts
  backend/core/src/secondary-adapters/postgres/channel-streaming/channel-streaming-repository-adapter.ts
  backend/core/src/secondary-adapters/postgres/chat/chat-repository-adapter.ts
  backend/core/src/shared/enums/messages/exception-messages.ts
  backend/core/src/shared/types/channel/channel.ts
  backend/core/src/shared/types/video/video-with-channel-and-author-dto.type.ts
  backend/core/src/shared/types/video/video.ts
  backend/push/src/config/amqp-connection.ts
  backend/push/src/services/socket/socket-service.ts
  frontend/src/common/config/socket.ts
  package-lock.json
  shared/src/common/enums/amqp/amqp-channel.enum.ts
  shared/src/common/enums/api/channel-streaming-api-path.enum.ts
  shared/src/common/enums/socket/socket-events.ts
  shared/src/common/types/channel/change-chat-toggle-request-dto.type.ts
  shared/src/common/types/channel/change-chat-toggle-response-dto.type.ts
  shared/src/common/types/channel/channel.ts
Labels: enhancement, docker, push-server, core-server, frontend, root, shared

#182 Task/backend209 following page
  backend/core/src/core/following/application/following-service.ts
  backend/core/src/core/following/following-container-module.ts
  backend/core/src/core/video/port/video-repository-filters.ts
  backend/core/src/core/video/port/video-repository.ts
  backend/core/src/primary-adapters/rest/following/following-controller.ts
  backend/core/src/primary-adapters/rest/rest-container-module.ts
  backend/core/src/secondary-adapters/postgres/video/video-repository-adapter.ts
  backend/core/src/shared/enums/api/api.ts
  backend/core/src/shared/types/container-type-keys.ts
  backend/core/src/shared/types/types.ts
  backend/core/src/shared/types/video/video.ts
  frontend/src/assets/img/bed-in-circle.svg
  frontend/src/common/enums/api/api.ts
  frontend/src/common/types/video/video.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/button/styles.module.scss
  frontend/src/components/common/loader/loader.tsx
  frontend/src/components/common/mobile-sidebar/mobile-sidebar.tsx
  frontend/src/components/common/sidebar/route-pages.config.ts
  frontend/src/components/common/sidebar/sidebar.tsx
  frontend/src/pages/following-page/following-page.tsx
  frontend/src/pages/following-page/styles.module.scss
  frontend/src/pages/following-page/tabs/common/no-videos-yet/no-videos-yet.tsx
  frontend/src/pages/following-page/tabs/common/no-videos-yet/styles.module.scss
  frontend/src/pages/following-page/tabs/live-videos/live-videos-tab.tsx
  frontend/src/pages/following-page/tabs/offline-videos/offline-videos-tab.tsx
  frontend/src/pages/following-page/tabs/overview/block-container/block-container.tsx
  frontend/src/pages/following-page/tabs/overview/block-container/header/header.tsx
  frontend/src/pages/following-page/tabs/overview/block-container/header/styles.module.scss
  frontend/src/pages/following-page/tabs/overview/block-container/styles.module.scss
  frontend/src/pages/following-page/tabs/overview/constants.ts
  frontend/src/pages/following-page/tabs/overview/live-block/live-block.tsx
  frontend/src/pages/following-page/tabs/overview/offline-block/offline-block.tsx
  frontend/src/pages/following-page/tabs/overview/overview-tab.tsx
  frontend/src/pages/following-page/tabs/overview/scrollable-videos-list/scrollable-videos-list.tsx
  frontend/src/pages/following-page/tabs/overview/scrollable-videos-list/styles.module.scss
  frontend/src/pages/following-page/tabs/overview/styles.module.scss
  frontend/src/pages/following-page/tabs/tab-button/styles.module.scss
  frontend/src/pages/following-page/tabs/tab-button/tab-button.tsx
  frontend/src/pages/following-page/tabs/tab-header/styles.module.scss
  frontend/src/pages/following-page/tabs/tab-header/tab-header.tsx
  frontend/src/pages/following-page/tabs/tab-info.ts
  frontend/src/pages/following-page/tabs/tab.ts
  frontend/src/services/following-api/following-api.service.ts
  frontend/src/services/services.ts
  frontend/src/store/following-page/actions.ts
  frontend/src/store/following-page/common.ts
  frontend/src/store/following-page/reducer.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/store.ts
  shared/src/common/enums/api/api-path.enum.ts
  shared/src/common/enums/api/api.ts
  shared/src/common/enums/api/following-api-path.enum.ts
  shared/src/common/types/following/following.ts
  shared/src/common/types/following/videos-live-response-dto.ts
  shared/src/common/types/following/videps-offline-response-dto.ts
  shared/src/common/types/types.ts
Labels: core-server, frontend, shared

#184 Task/backend208 disable chat
  .github/workflows/deploy-dev.yml
Labels: fix, ci/cd

#185 common: + tests
  .gitignore
  .ls-lint.yml
  package-lock.json
  package.json
  tests/README.md
  tests/index.d.ts
  tests/package.json
  tests/reporter.config.json
  tests/scripts/merge-api-reports.js
  tests/scripts/run-allure-generation.js
  tests/tests/api/config/dev.config.ts
  tests/tests/api/config/ppr.config.ts
  tests/tests/api/lib/controllers/auth.controller.ts
  tests/tests/api/lib/controllers/channel.controller.ts
  tests/tests/api/lib/controllers/channel.streming.controller.ts
  tests/tests/api/lib/controllers/history.controller.ts
  tests/tests/api/lib/controllers/profile.controler.ts
  tests/tests/api/lib/controllers/user.controller.ts
  tests/tests/api/lib/controllers/users.controller.ts
  tests/tests/api/lib/controllers/video.controller.ts
  tests/tests/api/lib/controllers/videos.controller.ts
  tests/tests/api/lib/request.ts
  tests/tests/api/specs/autorization_api-test.ts
  tests/tests/api/specs/data/schemas_testData.json
  tests/tests/api/specs/positive_api-test.ts
  tests/tests/helpers/functionsForChecking.helpers.ts
  tests/tsconfig.json
Labels: root

#183 Task/frontend56 implement full text search in postgres
  backend/core/prisma/migrations/20220829185929_add_index_for_video/migration.sql
  backend/core/prisma/schema.prisma
  backend/core/src/core/video/application/video-service.ts
  backend/core/src/core/video/port/video-repository.ts
  backend/core/src/primary-adapters/rest/video/video-controller.ts
  backend/core/src/secondary-adapters/postgres/video/video-repository-adapter.ts
  backend/core/src/shared/enums/enums.ts
  backend/core/src/shared/enums/video/video-filters-data.config.ts
  backend/core/src/shared/enums/video/video.ts
  backend/core/src/shared/helpers/video/date-helper.ts
  backend/core/src/shared/types/container-type-keys.ts
  backend/core/src/shared/types/video/video-with-channel-dto.type.ts
  backend/core/src/shared/types/video/video.ts
  shared/src/common/enums/api/video-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/search/search-models.enum.ts
  shared/src/common/enums/search/search.ts
  shared/src/common/types/video/base-video-response-dto.type.ts
  shared/src/common/types/video/video.ts
Labels: core-server, shared
